spring:
  application:
    name: msclientes

#0 pois assim cria portas randomicas sem um numero definido.
server:
  port: 0
#se conectando ao eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
